apiVersion: apps/v1
kind: Deployment
metadata:
  name: keyclock-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: keyclock-app
  template:
    metadata:
      labels:
        app: keyclock-app
    spec:
      containers:
      - name: keyclock-app
        image: quay.io/keycloak/keycloak:23.0.3
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: KC_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
        - name: KC_DB_URL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_URL
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
        - name: KC_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: KC_DB_SCHEMA
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_SCHEMA
        - name: KEYCLOAK_ADMIN
          valueFrom:
            secretKeyRef:
              name: keyclock-secret
              key: KEYCLOAK_ADMIN
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keyclock-secret
              key: KEYCLOAK_ADMIN_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: keyclock-service
spec:
  selector:
    app: keyclock-app
  ports:
  - port: 80
    targetPort: 8080

        
